### ISSUE TITLE
Error when i try load monogame xnb files

### ISSUE THREAD

**Issue by androidgtafan** [Athari/XnaConvert#8]
Hello! I want to edit android game xnb files. It seems that this xnb files was build by monogame studio. When I try to convetr them to png ther is error: Content loader for 'FDS' with version '4' not found. Please, help me.

**Comment by Athari** [comment]
Could you provide a sample file?

I think MonoGame uses the same format as the latest XNA (considering it relies on XNA content pipeline), but I'm not sure. There could be differences between platforms.

**Comment by androidgtafan** [comment]
Thanks for fast answer. Yes, of course. This is original file https://mega.co.nz/#!yMtSlDAT!0AfDhAL8SQ06Pct0GH8f2Nv2GMeEffYo0sROX9H1ZKA
and I try to decomress it with StarKit13c and get this https://mega.co.nz/#!yckSQCqJ!Rs9Y8vrGvFP8bawBKcv2hdXJ5G_Uv192F1mc6kCgbr8

StarKit13c link http://stardrivegame.com/forum/viewtopic.php?p=42356

**Comment by Athari** [comment]
The error message says:

> Failed to save file. Error loading "1.xnb". Cannot find ContentTypeReader **Fds.Framework.Content.Texture2DReader, Fds.Framework**.

It means that the game uses custom content format which is specific to that game. Alba.XnaConverter supports only files created using defult content pipeline, because custom content can contain absolutely any data.

If the game isn't protected, it should be possible to load its libraries into your own application and try reading the files, but it's out of scope of this tool, sorry.
